CREATE TABLE `sensor` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `board_id` int(2) UNSIGNED DEFAULT NULL,
  `A0` int(4) UNSIGNED DEFAULT NULL,
  `A1` int(4) UNSIGNED DEFAULT NULL,
  `A2` int(4) UNSIGNED DEFAULT NULL,
  `A3` int(4) UNSIGNED DEFAULT NULL,
  `A4` int(4) UNSIGNED DEFAULT NULL,
  `A5` int(4) UNSIGNED DEFAULT NULL,
  `millis` int(10) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
