# https://janiserdmanis.org/blog/digispark/index.html

# Hmmmm
# Does not work (yet), how to fix it?

BOARD_TAG    = mhetlive.avr.MHETtiny88
#USER_LIB_PATH+=./libs
#ARDUINO_LIBS += SendOnlySoftwareSerial

#ALTERNATE_CORE_PATH = ~/bin/DigistumpArduino/digistump-avr
#ARDUINO_CORE_PATH = ~/bin/DigistumpArduino/digistump-avr/cores/tiny
#ARDUINO_DIR = ~/bin/DigistumpArduino/digistump-avr
#MCU = attiny85
#ISP_PROG = ~/bin/micronucleus/commandline/micronucleus
#F_CPU = 16000000L

include /usr/share/arduino/Arduino.mk
