#!/bin/sh
while /bin/true; do
  socat -d -d /dev/ttyUSB0,b9600 exec:./mqtt_io
  #socat -d -d -d /dev/ttyUSB0,b9600 exec:./mqtt_io
  #socat -d -d -v /dev/ttyUSB0,b9600 exec:./mqtt_io
  pkill -e -A -s 0
  sleep 5
done
